export const API_ERROR = {
  MOVIE_NOT_FOUND: 'MOVIE_NOT_FOUND',
  MOVIE_DETAILS_NOT_FOUND: 'MOVIE_DETAILS_NOT_FOUND',
  SERVICE_ERROR: 'SERVICE_ERROR'
}

export const FAVORITES_STORAGE_KEY = 'liveSearchFavorites'
